use Django serializer for dumps
nnseva/django-jsoneditor pull request #68
Opened 2022-09-08 14:49 UTC by norton120

This helps to handle things like date objects that will cause the dreaded "datetime.date not JSON serializable" error. 

I tried to get the test sites working to use existing tests, but I couldn't get the requirements to play nice and I eventually just plugged it into my downstream project. 
Before: 
![Screenshot from 2022-09-08 10-48-48](https://user-images.githubusercontent.com/6440476/189153657-69104d6f-82f2-4ad1-ac83-321fee1decc1.png)

After: 
![Screenshot from 2022-09-08 10-44-57](https://user-images.githubusercontent.com/6440476/189152882-d5548980-dc41-4dd0-977c-0e7942885bb9.png)

2022-09-08 14:53 UTC, norton120 commented
If there are some contribution docs I missed feel free to point me in that direction - I def want to make sure I set this up right, really appreciate the library!

2022-10-01 12:59 UTC, norton120 commented
hey @nnseva any feelings about this PR? I am using a fork for now but I'd love to get back on the mainline, let me know if I am missing any contribution steps

2022-10-01 18:14 UTC, nnseva requested changes
Hi! It's a good proposal, would you like to allow to choose a custom encoder while the widget construction? use the init method like the jsonschema does, and pass a custom encoder, such a way, the Django encoder might be an option on the application level. The default encoder should stay untouched.

Create couple of lines in the readme about custom encoder with some practical example.

2022-10-09 16:40 UTC, norton120 commented
> Hi! It's a good proposal, would you like to allow to choose a custom encoder while the widget construction? use the init method like the jsonschema does, and pass a custom encoder, such a way, the Django encoder might be an option on the application level. The default encoder should stay untouched.
> 
> Create couple of lines in the readme about custom encoder with some practical example.

Great feedback thank you! 
Updated to part of the init method (`json.dumps` defaults to None so I think it's safe to pass directly through, a change to that default would be breaking on the corelib side so it seems safe)

also update the README with an example. THanks!

2022-10-10 16:38 UTC, nnseva approved these changes

2022-10-10 16:39 UTC, merged